name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

  Build:
    name: Lint, unit tests, SonarCloud
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn lint
      - run: yarn test:coverage
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Export:
    name: "Export, e2e tests"
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn generate # static files generation
      - run: yarn cy:verify # check that Cypress can run
      - run: yarn start & # start server in the background
      - run: yarn cy:run --record # run all Cypress tests and record on the dashboard
